// Generated by https://quicktype.io

export interface GasStationMap {
  radius_parameter: string;
  stations:         Station[];
}

export interface Station {
  id:           string;
  flag_id:      string;
  latitude:     number;
  longitude:    number;
  fantasy_name: string;
  street:       string;
  number:       string;
  distance:     number;
  flag:         Flag;
  products:     Product[];
}

export interface Flag {
  id:     string;
  logo:   string;
  marker: null;
  uri:    string;
}

export interface Product {
  product_id:      string;
  name:            string;
  flag_id:         null;
  price:           number;
  product_default: boolean;
}
