export enum ParameterEnum {
  INITIAL_MESSAGE = 0,
  MAX_METERS_LOCALIZATION = 1,
  DEFAULT_PRODUCT_ID = 3,
  PATH_LOGO_POST_MELHOR = 8,
  MAX_AMOUNT_STATION = 9,
  MIN_DISTANCE_LOCALIZATION = 10,
  MAX_DISTANCE_LOCALIZATION = 11
}
